#!/bin/bash

sudo yum install -y tmux
sudo yum install -y httpd
sudo yum install -y mysql-server

sudo systemctl start httpd
sudo systemctl enable httpd
sudo systemctl start mysql
sudo systemctl enable mysql

mkdir -p /tmp/part6
cd /tmp/part6

url="https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/"
packages=$(curl -s -L "$url" | grep -o 'href="[^"].*4\.9.*rpm"' |sed  's/\(^......\)\|\(.$\)//g')

packages=$(echo $packages | tr '\n' ' ')

for package in $packages
do
  wget "$url$package"
done

sudo yum install createrepo

sudo mkdir /var/www/html/zabbix-local
sudo mv /tmp/part6/*.rpm /var/www/html/zabbix-local

cat << EOF >> /etc/yum.repos.d/zabbix-local.repo
[zabbix-local]
name=zabbix-local
baseurl=file:///var/www/html/zabbix-local/
gpgcheck=0
enabled=1
EOF

yum clean all
yum install --disablerepo=* --enablerepo="zabbix-local"  zabbix-release zabbix-agent2 zabbix zabbix-get zabbix-js zabbix-server zabbix-sender zabbix-web-mysql






